name: GithubActionsWIP

on:
  push:
    branches:
      - 'main'

  pull_request:
    branches:
      - 'main'

env:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  output: ${{github.workspace}}/output
  project: 'GoogleAnalytics.Blazor/GoogleAnalytics.Blazor.csproj'

jobs:

############################################################################################################
# Build GA.B
############################################################################################################
  build-gab:
    name: Build GoogleAnalytics.Blazor
    runs-on: windows-latest

    steps:
    - name: Set ciSuffix as env variable
      run: echo "ciSuffix=ci.$(date +'%Y-%m-%d--%H%M')" >> $GITHUB_ENV
      shell: bash

    - name: Checkout repository under $GITHUB_WORKSPACE so the job can access it 🛎️
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Use prelease dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Publish GA.B 🔧
      run: dotnet publish ${{env.project}} --configuration ${{env.buildConfiguration}} --output ${{env.output}} --version-suffix ${{env.version}} -p:BlazorEnableCompression=false

    - name: Generate the NuGet package 🔧
      run: dotnet pack ${{env.project}} --no-build --configuration ${{env.buildConfiguration}} --output ${{env.output}} -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -p:Version=1.0.0-${{env.version}}

    - name: Display package output Ꙫ
      run: dir ${{env.output}}

# We'd like to push to a the main repository but now getting errors of authorization

    - name: Upload Package (Main repository) 🔺
      run: nuget push ${{env.output}}\*.nupkg -Source https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      if: (github.repository == 'Material-Blazor/GoogleAnalytics.Blazor') && (github.event_name == 'push') && false

# We'd like to push to a forked repository; The push appears to work but the packages are not visible
# Pending a service response we only do the push of the CI build in the Material-Blazor/GoogleAnalytics.Blazor repository

    - name: Upload Package (Forked repository) 🔺
      run: nuget push ${{env.output}}\*.nupkg -Source https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GH_PAT}}
      if: (github.repository != 'Material-Blazor/GoogleAnalytics.Blazor') && (github.event_name == 'push') && false
